---
title: "Example3"
output: html_document
editor_options: 
  chunk_output_type: console
---


### Simplify a series of operations using abstraction
```{r warning = FALSE, message = FALSE}
library(palmerpenguins)
head(penguins)
```


### Option A: Run three linear models with diagnostics
```{r eval = F}
m1 <- lm(body_mass_g ~ island, data = penguins)
fit1 <- anova(m1)
normality <- shapiro.test(residuals(m1))

m2 <- lm(body_mass_g ~ year + sex, data = penguins)
fit2 <- anova(m2)
normality <- shapiro.test(residuals(m2))

m3 <- lm(body_mass_g ~ species * island, data = penguins)
fit3 <- anova(m3)
normality <- shapiro.test(residuals(m3))
```

### Option B: Create a function for models
```{r eval = F}
getModelAndDiagnostics <- function(predictors, response) {
  
formulaTest <- formula(paste0(response, " ~ ", predictors))

m0 <- lm(formulaTest, data = penguins)
fit0 <- anova(m0)
normality <- shapiro.test(residuals(m0))

modelOut <- data.frame(fit0, 
                       normalStat = normality$statistic,
                       normalPval = normality$p.value)
return(modelOut)
}

getModelAndDiagnostics("island", "body_mass_g")
getModelAndDiagnostics("year + sex", "body_mass_g")
getModelAndDiagnostics("species * island", "body_mass_g")

```

### Option C: Create a loop to use function
```{r eval = F}
modelTests <- c("island", "year + sex", "species * island")

outModels <- data.frame()
for(modelTest in modelTests){
  outModel <- getModelAndDiagnostics(modelTest, "body_mass_g")
  outModels <- rbind(outModels, outModel)
}
outModels
```