---
output:
  html_document: default
  pdf_document: default
  word_document: default
---
## Example3abstraction



### Original
```{r eval = F}
## Assign spatial coordinates
coordinates(sp1) <- ~decimalLongitude + decimalLatitude ## Transform occurrences to spdataframe
proj4string(sp1) <- CRS("+proj=longlat +datum=WGS84")
sp1 <- spTransform(sp1, crs(climateRasters))

## Extract climate data
allClim <- extract(climateRasters, sp1)
allClimDF <- data.frame(allClim)

## Check for multicollinearity
collinear <- usdm::vifcor(allClimDF[,-ncol(allClimDF)])
selectVars <-  collinear@results$Variables

colinearVariables <- climateRasters[[selectVars]]
```

### One level of abstraction
```{r  eval = F}
sp1 <- assignSpatialCoordinates(sp1)

allClimDF <- getClimateDataframe(sp1)

selectVars <- findCollinear(allClimDF)

collinearVariables <- climateRasters[[selectedVars]] 
```


### Second level of abstraction
```{r  eval = F}
selectedVars <- findCollinearVariables(sp1, climateRasters)
collinearVariables <- climateRasters[[selectedVars]] 
```


### New Abstraction version
```{r  eval = F}
library(terra)

## Data load
speciesOccurrences <- vect("occurrence_points.shp")
speciesAbsences <- vect("absence_points.shp")
climateData <- rast("./climateData.tif")

## Climate extraction
occurenceClimate <- extract(climateData, speciesOccurrences)
absenceClimate <- extract(climateData, speciesAbsences)
allClimate <- rbind(occurenceClimate, absenceClimate)
allClimate[,"speciesRecord"] <- c(rep(1, nrow(occurenceClimate)),rep(0, nrow(occurenceClimate)))

## Data cleaning
allClimateNAremoved <- allClimate[complete.cases(allClimate),]
allClimateNADupsremoved <- allClimateNAremoved[!duplicated(allClimateNAremoved),]

## Check for multicollinearity
collinear <- usdm::vifcor(allClimateNADupsremoved[-ncol(allClimateNADupsremoved)])
removeVariables <-  collinear@excluded
allClimateModelReady <-  allClimateNADupsremoved[!names(allClimateNADupsremoved) %in% removeVariables]

## Run logistic regression
modelOut <- glm(speciesRecord ~ ., data = allClimateModelReady, family = binomial)
summary(modelOut)


```

### One level of Abstraction
```{r  eval = F}
extractClimateFromPoints <- function(occ, abs, climate) {
occurenceClimate <- extract(climate, occ)
absenceClimate <- extract(climate, abs)
climateDF <- rbind(occurenceClimate, absenceClimate)
climateDF[,"speciesRecord"] <- c(rep(1, nrow(occurenceClimate)),rep(0, nrow(occurenceClimate)))
return(climateDF)
}

cleanRecords <- function(climateDF) {
climateDF <- climateDF[complete.cases(climateDF),] 
climateDF <- climateDF[!duplicated(climateDF),]
return(climateDF)
} 

checkCollinear <- function(climateDF) {
collinear <- usdm::vifcor(climateDF[-ncol(climateDF)])
removeVariables <-  collinear@excluded
climateVariables <- climateDF[!names(climateDF) %in% removeVariables,]
return(climateVariables)
}

climateLogisticRegression <- function(processedClimateDF) {
model <- glm(speciesRecord ~ ., data = processedClimateDF, family = binomial)
print(summary(model))
return(model)
}

allClimate <- extractClimateFromPoints(speciesOccurrences, speciesAbsences, climateData)

allClimateNADupsremoved <- cleanRecords(allClimate)

allClimateModelReady <- checkCollinear(allClimateNADupsremoved)

modelOut <- climateLogisticRegression(allClimateModelReady)

```

### Second level of abstraction
```{r  eval = F}

runClimateLogisticRegression <- function(occ, abs, climate) {
allClimate <- extractClimateFromPoints(speciesOccurrences, speciesAbsences, climateData)
allClimateNADupsremoved <- cleanRecords(allClimate)
allClimateModelReady <- checkCollinear(allClimateNADupsremoved)
climateLogisticRegression(allClimateModelReady)
return(climateLogisticRegression)
}

runClimateLogisticRegression(speciesOccurrences, speciesAbsences, climateData)
```